<h1><?php echo $this->translate('Users') ?></h1>

<div class="navbar filter-bar">
    <div class="navbar-inner">
        <div class="pull-right">
            <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/create') ?>" class="btn btn-primary">
                <?php echo $this->translate('Add New User') ?>
            </a>
        </div>
    </div>
</div>

<?php echo $this->table($table) ?>

<!---

    <tfoot>
    <tr>
        <td colspan="<?php echo count($this->userlistElements) + 1; ?>">
            <?php // echo $this->paginationControl($this->users, 'Sliding', 'zfc-user-admin/user-admin/pagination_userlist.phtml'); ?>
        </td>
    </tr>
    </tfoot>

-->